apiVersion: 1
datasource:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-operated.observability.svc.cluster.local:9090
    isDefault: true
  - name: Loki
type: loki
access: proxy
url: http://loki.observability.svc.cluster.local:3100