# Minimal overrides for kube-prometheus-stack
prometheus:
prometheusSpec:
evaluationInterval: "30s"
scrapeInterval: "30s"
ruleSelectorNilUsesHelmValues: false
retention: "15d"
storageSpec:
volumeClaimTemplate:
spec:
accessModes: ["ReadWriteOnce"]
resources:
requests:
storage: 20Gi


# alertmanager config via Alertmanager CRD managed by operator
alertmanager:
alertmanagerSpec:
replicas: 3
config: |
global:
resolve_timeout: 5m
route:
group_by: ['alertname', 'namespace']
group_wait: 30s
group_interval: 5m
repeat_interval: 4h
receiver: 'slack'
receivers:
  - name: 'slack'
slack_configs:
  - api_url: 'https://hooks.slack.com/services/XXX/YYY/ZZZ'
channel: '#alerts'